# Generated by Django 3.2.10 on 2022-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20211225_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
